In [21]:
import numpy as np

In [24]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_copy = arr.copy()

In [27]:
arr_copy[1:5] = 10

In [28]:
arr_copy

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
arr_2d[1,1]

5

In [33]:
arr_2d[1][1]

5

In [34]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [35]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [36]:
arr = np.arange(1,11)